# Generated by Django 4.1 on 2023-11-03 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["completed"]},
        ),
    ]
